---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}/{{ ansible_distribution_release|lower }}/main.yml"
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}/main.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - main.yml
  tags:
    - always

- name: "Install for {{ ansible_os_family }}"
  include: "{{ ansible_os_family|lower }}/{{ ansible_pkg_mgr|lower }}-install.yml"
  when: '"docker" not in groups'

- name: Copy HAProxy cfg (debug)
  template:
    src: haproxy.cfg.j2
    dest: "{{ etc_prefix }}/haproxy/haproxy.cfg.debug"
  when:
    - haproxy_manage_config
    - debug_mode
  become: true
  tags:
    - debug

- name: Copy HAProxy cfg
  template:
    src: haproxy.cfg.j2
    dest: "{{ etc_prefix }}/haproxy/haproxy.cfg"
    # validate: haproxy -f %s -c -q
  when: haproxy_manage_config
  notify:
    - restart haproxy
    - restart haproxy docker
  become: true
  tags:
    - config

- name: "Start HAProxy Docker container"
  docker_container:
    image: haproxy:1.7-alpine
    name: haproxy
    networks:
      - name: jenkins_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy:ro
  register: haproxy_docker_container
  when: '"docker" in groups'
